// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPE3WTyGI-QgPeHRjj5rJOLJw5uAlPvo',
    appId: '1:471486445105:web:d34f11021c254670370710',
    messagingSenderId: '471486445105',
    projectId: 'protection-x',
    authDomain: 'protection-x.firebaseapp.com',
    storageBucket: 'protection-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7QiDX0qS6B-nnMjMkw4LZvRWmbFHNsb4',
    appId: '1:471486445105:android:143a5e66d48b423f370710',
    messagingSenderId: '471486445105',
    projectId: 'protection-x',
    storageBucket: 'protection-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSdNna79m58bM0jpqtUbhqtJVeqULP8E',
    appId: '1:471486445105:ios:cc311b5ca952a713370710',
    messagingSenderId: '471486445105',
    projectId: 'protection-x',
    storageBucket: 'protection-x.appspot.com',
    iosBundleId: 'com.example.protectionx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhSdNna79m58bM0jpqtUbhqtJVeqULP8E',
    appId: '1:471486445105:ios:cc311b5ca952a713370710',
    messagingSenderId: '471486445105',
    projectId: 'protection-x',
    storageBucket: 'protection-x.appspot.com',
    iosBundleId: 'com.example.protectionx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiPE3WTyGI-QgPeHRjj5rJOLJw5uAlPvo',
    appId: '1:471486445105:web:6c94d7e862fb51b9370710',
    messagingSenderId: '471486445105',
    projectId: 'protection-x',
    authDomain: 'protection-x.firebaseapp.com',
    storageBucket: 'protection-x.appspot.com',
  );
}
